<?php

use PHPUnit\Framework\TestCase;
use todo\model\Task;
use todo\model\User;
use todo\components\Db;
use RedBeanPHP\R;

class TaskTest extends TestCase
{
    private $taskModel;
    private $postData;

    public function setUp(): void
    {
        $this->taskModel = new Task();
        $this->postData = $this->preparePostData();
        $this->createDummyUser();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown(): void
    {
        R::exec( "DELETE from task WHERE user_id = {$_SESSION['user']}" );
        R::exec( "DELETE from subtask WHERE user_id = {$_SESSION['user']}" );
        R::exec( "DELETE from user WHERE id = {$_SESSION['user']}" );
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testAddTask()
    {
        $response = $this->taskModel->addTask($this->preparePostData());



        var_dump($response);

        $this->assertEquals($response['data'], 'Task Successfully added');
    }

    private function preparePostData()
    {
        $dummyData = array(
            "header" => "example",
            "text" => "example body",
            "date" => date('Y-m-d', strtotime('tomorrow')),
            "status" => "1"
        );

        return $dummyData;
    }

    private function createDummyUser()
    {
        Db::getConnection();
        $user = new User();
        $user->userRegister('test@test.com', "11773626");
    }

}
